### ISSUE TITLE
Crash when input lines exceeded max padding

### ISSUE THREAD

**Issue by DaPa** [Caphyon/clang-format-editor#14]
Nice app, thanks for it!

I got a crash when some lines exceeded 600 chars or so: then I tried a quick fix into https://github.com/DaPa/clang-format-editor/commit/b511cd2eab8330bd29df7fda48090b1dba41656a

Then I also made a change to avoid padding, as I saw it unnecessary (just my taste) so instead I opted to trim ending white spaces (https://github.com/DaPa/clang-format-editor/commit/3e170ed98a08eeda568656e93ff04f38f4117085): but not sure if there are side effects (not sure if this padding is required in certain scenarios).

**Comment by hprica** [comment]
Hello @DaPa, 

Thank you for using the app and for your feedback. We'll look into the issue as soon as possible.

If you have any feature suggestions, please let me know.

**Comment by hprica** [comment]
Fixed in #15
