### ISSUE TITLE
i can not use tool

### ISSUE THREAD

**Issue by Hungpro3112** [Caphyon/clang-format-editor#18]
i open file test.cpp but when i hit a button to modify this tool absolutely close. I don't know why this happen.
https://user-images.githubusercontent.com/75968004/127254815-161f3de5-ccbf-40aa-825f-8d8f7eecb295.mp4
Thanks for your help

**Comment by hprica** [comment]
Hello @Hungpro3112,

Thank you for reporting the issue.

I apologize for the late reply. We had some issues due to the new LLVM 12.0.1 format options. A release will be coming this week to fix this issue. We'll let you know when the update is deployed.

**Comment by hprica** [comment]
@Hungpro3112, the release has been published. Open the Editor and the Updater should prompt you to install the update. 

Let me know if you find any issues.
