### ISSUE TITLE
Error message when switching between predefined styles

### ISSUE THREAD

**Issue by ifarbod** [Caphyon/clang-format-editor#27]
I'm not sure if it only happens to me or not, to reproduce this, type something in the `Quick search` input field at the top left, for example, `Align`. then try to switch between Google and LLVM in the `Select Style` dropdown. You'll get a strange error message box that doesn't make sense:

![Object reference not set to an instance of an object](https://user-images.githubusercontent.com/4181752/179043873-a53be100-5945-48e4-bab6-3cf6425e30d0.png)
<sup> **Alt:** Object reference not set to an instance of an object. </sup>

Offtopic: What's the timeline like, for upgrading to .NET 7 and LLVM/ClangFormat 15?

**Comment by ix-anemoff** [comment]
Same error here when changing option values.

**Comment by mariru27** [comment]
Hi @ifarbod, @ix-anemoff,

A fix for this issue is available in Clang Format Editor v2023.4.2

Thank you for reporting this problem

Kind regards,
Marina
