### ISSUE TITLE
Weird error on selecting a few C++ headers

### ISSUE THREAD

**Issue by PerikiyoXD** [Caphyon/clang-format-editor#40]
![imagen](https://github.com/Caphyon/clang-format-editor/assets/3116368/baefedbc-15f1-47e3-a8d4-bf763192c603)
If you need anything, please don't hesistate on commenting back

**Comment by PerikiyoXD** [comment]
Related with #39

**Comment by mariru27** [comment]
Hi @PerikiyoXD,

Thank you for reporting this problem, we are working on a fix

Kind regards,
Marina

**Comment by mariru27** [comment]
@PerikiyoXD, what version of Clang Format Editor you using?

**Comment by mariru27** [comment]
Hi @PerikiyoXD,

A fix for this issue is available in Clang Format Editor v2023.4.2

Thank you for reporting this problem

Kind regards,
Marina
