### ISSUE TITLE
Enable format detector's diff view in format editor

### ISSUE THREAD

**Issue by Martin-B-Git** [Caphyon/clang-format-editor#8]
I would like to use the diff view from the clang format detector also in the clang format editor. 

The current view in the format editor with two separate tabs for unformatted and reformatted file makes it really hard to discuss changes to format settings on an existing code project with your colleagues. 
You cannot even show the two tabs side by side. Therefore you have to continuously switch between tabs to figure out all the differences that your change to the format file caused. The diff view would solve that problem.

**Comment by hprica** [comment]
Hello @Martin-B-Git,

I apologize for the late response and thank you for the suggestion. 

We will have a small point release coming soon. Afterward, I will start working on this enhancement.

If you have any other feedback, let me know.

**Comment by hprica** [comment]
@Martin-B-Git, your suggestion was implemented in 7.3.0. The update will be automatically launched when opening the Editor.
